### ISSUE TITLE
How do I start the server?

### ISSUE THREAD

**Issue by AidenEllis** [polygonnedpotato/pyrock#1]
A descriptive README would be appreciative.

**Comment by AidenEllis** [comment]
This doesn't work wth?!

**Comment by polygonnedpotato** [comment]
this project was going to be an attempt to make a bedrock server with python.

i have abandoned this project due to a lack of interest in persuing this.

**Comment by AidenEllis** [comment]
Awe okay. I think you should definitely make this repo Private, or it'll pop up on Google search results.
